---
:backends:
  - yaml
  - trocla

:hierarchy:
  - hosts/%{fqdn}
  - node_types/%{node_type}
  - locations/%{location}
  - vagrant
  - defaults
:yaml:
   :datadir: /etc/puppet/ibox/hieradata
:trocla:
  :config: /etc/puppet/troclarc.yaml
